name: hero_games_flutter_task
description: A new Flutter project.
publish_to: 'none' 
version: 1.0.0+1

environment:
  sdk: '>=3.1.2 <4.0.0'
dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  flutter_launcher_icons: ^0.13.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/images/hero_logo.png"
  min_sdk_android: 21
  web:
    generate: true
    image_path: "assets/images/hero_logo.png"
    background_color: "#000000"
    theme_color: "#000000"
flutter:
  uses-material-design: true
  assets:
     - assets/images/
     - assets/icons/